<a href="https://colab.research.google.com/github/giossaurus/tensorflow-deep-learning-studies/blob/main/00_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Tópicos desse caderno:
- Introdução aos tensores
- Pegar as info dos tensores
- Manipular tensores
- Tensores e NumPy
- Usa da @tf.function
- Uso de GPUs ou TPUs com TensorFlow
- Exercicios

In [1]:
import tensorflow as tf
print(tf.__version__)

2.19.0


In [3]:
#Criando tensores com tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [4]:
#Numero de dimensoes do tensor (ndim)
scalar.ndim

0

In [5]:
#Criando um vetor
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [6]:
#Dimensão do vetor
vector.ndim

1

In [8]:
#Matriz
matrix = tf.constant([[10, 7],
                     [7, 10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>