<a href="https://colab.research.google.com/github/giossaurus/tensorflow-deep-learning-studies/blob/main/00_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Tópicos desse caderno:
- Introdução aos tensores
- Pegar as info dos tensores
- Manipular tensores
- Tensores e NumPy
- Usa da @tf.function
- Uso de GPUs ou TPUs com TensorFlow
- Exercicios

In [2]:
import tensorflow as tf
print(tf.__version__)

2.19.0


In [3]:
#Criando tensores com tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [4]:
#Numero de dimensoes do tensor (ndim)
scalar.ndim

0

In [5]:
#Criando um vetor
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [6]:
#Dimensão do vetor
vector.ndim

1

In [7]:
#Matriz
matrix = tf.constant([[10, 7],
                     [7, 10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [8]:
matrix.ndim

2

In [9]:
#Segunda matriz
another_matrix = tf.constant([[10.,7.],
                              [3.,2.],
                              [8.,9.]], dtype=tf.float16)
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [10]:
another_matrix.ndim

2

In [11]:
#Criando um tensor
#scaler tem 0 dim
#vector tem 1 dim
#matriz tem 2 dim
#tensor tem 3 ou mais

tensor = tf.constant([[[1, 2, 3,],
                       [4, 5, 6]],
                      [[7, 8, 9],
                       [10, 11, 12]],
                      [[13, 14, 15],
                       [16, 17, 18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [12]:
tensor.ndim

3

- Scalar é um numero singular
- Vector é um numero com direção (ex.: velocidade e direção do vento)
- Matrix é um array bi-dimensional de números
- Tensor é um array de números n-dimensional (onde n pode ser qualquer número, um tensor 0-dim é um scaler, um tensor 1-dim é um vector)

In [15]:
#Criando tensores com tf.Variable
changeable_tensor = tf.Variable([10,7])
unchangeable_tensor = tf.constant([10,7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [18]:
#Tentando mudar o elemento do tensor modificavel
#changeable_tensor[0] = 7
#changeable_tensor

changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [19]:
#Tentando mudar o elemento no tensor não modificavel
unchangeable_tensor[0].assign(7)
unchangeable_tensor

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

Dificilmente precisamos escolher se usaremos `tf.constant` ou `tf.Variable` para criar tensores, o TensorFlow faz isso já, mas na dúvida escolher `tf.constant` e caso necessário modificar depois

### Criando tensores aleatórios

São tensores que contém um tamanho arbitrário e de números aleatórios

In [21]:
#Criando dois tensores aleatorios (mas iguais)
random_1 = tf.random.Generator.from_seed(42)
random_1 = random_1.normal(shape=(3,2))
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3,2))

random_1, random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

In [31]:
#Embaralhar a ordem dos tensores
#Bom para quando você quer embaralhar os dados então a ordem dos itens não afeta o aprendizado

not_shuffled = tf.constant([[10,7],
                           [3,4],
                           [2,5]])
not_shuffled.ndim

tf.random.set_seed(42)
tf.random.shuffle(not_shuffled, seed = 42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [ ]:
#Exercicio: Ler a doc do TensorFlow sobre random seed
#Praticar com a escrita de 5 tensores aleatorios e embaralhar eles